import type { Config } from "tailwindcss";
import animate from "tailwindcss-animate";

const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./features/**/*.{ts,tsx}",
    "./layouts/**/*.{ts,tsx}",
    "./providers/**/*.{ts,tsx}",
    "./hooks/**/*.{ts,tsx}",
    "./design-system/**/*.{ts,tsx}",
    "./lib/**/*.{ts,tsx}",
  ],
  theme: {
    container: {
      center: true,
      padding: {
        DEFAULT: "var(--space-5)",
        md: "var(--space-7)",
        lg: "var(--space-8)",
      },
      screens: {
        sm: "100%",
        md: "720px",
        lg: "960px",
        xl: "1140px",
        "2xl": "1440px",
      },
    },
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
          50: "var(--color-primary-50)",
          100: "var(--color-primary-100)",
          200: "var(--color-primary-200)",
          300: "var(--color-primary-300)",
          400: "var(--color-primary-400)",
          500: "var(--color-primary-500)",
          600: "var(--color-primary-600)",
          700: "var(--color-primary-700)",
          800: "var(--color-primary-800)",
          900: "var(--color-primary-900)",
        },
        neutral: {
          50: "var(--color-neutral-50)",
          100: "var(--color-neutral-100)",
          200: "var(--color-neutral-200)",
          300: "var(--color-neutral-300)",
          400: "var(--color-neutral-400)",
          500: "var(--color-neutral-500)",
          600: "var(--color-neutral-600)",
          700: "var(--color-neutral-700)",
          800: "var(--color-neutral-800)",
          900: "var(--color-neutral-900)",
        },
        success: {
          DEFAULT: "var(--color-success-500)",
          foreground: "var(--color-success-foreground)",
          50: "var(--color-success-50)",
          100: "var(--color-success-100)",
          200: "var(--color-success-200)",
          300: "var(--color-success-300)",
          400: "var(--color-success-400)",
          500: "var(--color-success-500)",
          600: "var(--color-success-600)",
          700: "var(--color-success-700)",
          800: "var(--color-success-800)",
          900: "var(--color-success-900)",
        },
        warning: {
          DEFAULT: "var(--color-warning-500)",
          foreground: "var(--color-warning-foreground)",
          50: "var(--color-warning-50)",
          100: "var(--color-warning-100)",
          200: "var(--color-warning-200)",
          300: "var(--color-warning-300)",
          400: "var(--color-warning-400)",
          500: "var(--color-warning-500)",
          600: "var(--color-warning-600)",
          700: "var(--color-warning-700)",
          800: "var(--color-warning-800)",
          900: "var(--color-warning-900)",
        },
        danger: {
          DEFAULT: "var(--color-danger-500)",
          foreground: "var(--color-danger-foreground)",
          50: "var(--color-danger-50)",
          100: "var(--color-danger-100)",
          200: "var(--color-danger-200)",
          300: "var(--color-danger-300)",
          400: "var(--color-danger-400)",
          500: "var(--color-danger-500)",
          600: "var(--color-danger-600)",
          700: "var(--color-danger-700)",
          800: "var(--color-danger-800)",
          900: "var(--color-danger-900)",
        },
        info: {
          DEFAULT: "var(--color-info-500)",
          foreground: "var(--color-info-foreground)",
          50: "var(--color-info-50)",
          100: "var(--color-info-100)",
          200: "var(--color-info-200)",
          300: "var(--color-info-300)",
          400: "var(--color-info-400)",
          500: "var(--color-info-500)",
          600: "var(--color-info-600)",
          700: "var(--color-info-700)",
          800: "var(--color-info-800)",
          900: "var(--color-info-900)",
        },
        ai: {
          DEFAULT: "var(--color-ai-500)",
          foreground: "var(--color-ai-foreground)",
          50: "var(--color-ai-50)",
          100: "var(--color-ai-100)",
          200: "var(--color-ai-200)",
          300: "var(--color-ai-300)",
          400: "var(--color-ai-400)",
          500: "var(--color-ai-500)",
          600: "var(--color-ai-600)",
          700: "var(--color-ai-700)",
          800: "var(--color-ai-800)",
          900: "var(--color-ai-900)",
        },
        job: {
          DEFAULT: "var(--color-job-500)",
          foreground: "var(--color-job-foreground)",
          50: "var(--color-job-50)",
          100: "var(--color-job-100)",
          200: "var(--color-job-200)",
          300: "var(--color-job-300)",
          400: "var(--color-job-400)",
          500: "var(--color-job-500)",
          600: "var(--color-job-600)",
          700: "var(--color-job-700)",
          800: "var(--color-job-800)",
          900: "var(--color-job-900)",
        },
        cyan: {
          DEFAULT: "var(--color-cyan-500)",
          foreground: "var(--color-cyan-foreground)",
          50: "var(--color-cyan-50)",
          100: "var(--color-cyan-100)",
          200: "var(--color-cyan-200)",
          300: "var(--color-cyan-300)",
          400: "var(--color-cyan-400)",
          500: "var(--color-cyan-500)",
          600: "var(--color-cyan-600)",
          700: "var(--color-cyan-700)",
          800: "var(--color-cyan-800)",
          900: "var(--color-cyan-900)",
        },
        cv: {
          DEFAULT: "var(--color-cv-500)",
          foreground: "var(--color-cv-foreground)",
          50: "var(--color-cv-50)",
          100: "var(--color-cv-100)",
          200: "var(--color-cv-200)",
          300: "var(--color-cv-300)",
          400: "var(--color-cv-400)",
          500: "var(--color-cv-500)",
          600: "var(--color-cv-600)",
          700: "var(--color-cv-700)",
          800: "var(--color-cv-800)",
          900: "var(--color-cv-900)",
        },
        analytics: {
          DEFAULT: "var(--color-analytics-500)",
          foreground: "var(--color-analytics-foreground)",
          50: "var(--color-analytics-50)",
          100: "var(--color-analytics-100)",
          200: "var(--color-analytics-200)",
          300: "var(--color-analytics-300)",
          400: "var(--color-analytics-400)",
          500: "var(--color-analytics-500)",
          600: "var(--color-analytics-600)",
          700: "var(--color-analytics-700)",
          800: "var(--color-analytics-800)",
          900: "var(--color-analytics-900)",
        },
        surface: {
          0: "var(--color-surface-0)",
          1: "var(--color-surface-1)",
          2: "var(--color-surface-2)",
          3: "var(--color-surface-3)",
        },
        glass: {
          bg: "var(--glass-bg)",
          border: "var(--glass-border)",
        },
        text: {
          primary: "var(--color-text-primary)",
          body: "var(--color-text-body)",
          secondary: "var(--color-text-secondary)",
          tertiary: "var(--color-text-tertiary)",
          disabled: "var(--color-text-disabled)",
          inverse: "var(--color-text-inverse)",
          link: "var(--color-text-link)",
          "link-hover": "var(--color-text-link-hover)",
          success: "var(--color-text-success)",
          warning: "var(--color-text-warning)",
          danger: "var(--color-text-danger)",
        },
        notification: {
          "info-bg": "var(--notification-info-bg)",
          "info-border": "var(--notification-info-border)",
          "info-text": "var(--notification-info-text)",
          "info-icon": "var(--notification-info-icon)",
          "success-bg": "var(--notification-success-bg)",
          "success-border": "var(--notification-success-border)",
          "success-text": "var(--notification-success-text)",
          "success-icon": "var(--notification-success-icon)",
          "warning-bg": "var(--notification-warning-bg)",
          "warning-border": "var(--notification-warning-border)",
          "warning-text": "var(--notification-warning-text)",
          "warning-icon": "var(--notification-warning-icon)",
          "error-bg": "var(--notification-error-bg)",
          "error-border": "var(--notification-error-border)",
          "error-text": "var(--notification-error-text)",
          "error-icon": "var(--notification-error-icon)",
          "neutral-bg": "var(--notification-neutral-bg)",
          "neutral-border": "var(--notification-neutral-border)",
          "neutral-text": "var(--notification-neutral-text)",
          "neutral-icon": "var(--notification-neutral-icon)",
          "ai-bg": "var(--notification-ai-bg)",
          "ai-border": "var(--notification-ai-border)",
          "ai-text": "var(--notification-ai-text)",
          "ai-icon": "var(--notification-ai-icon)",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
      },
      borderRadius: {
        xs: "var(--radius-xs)",
        sm: "var(--radius-sm)",
        md: "var(--radius-md)",
        lg: "var(--radius-lg)",
        xl: "var(--radius-xl)",
        "2xl": "var(--radius-2xl)",
        full: "var(--radius-full)",
      },
      boxShadow: {
        "1": "var(--shadow-1)",
        "2": "var(--shadow-2)",
        "3": "var(--shadow-3)",
        "4": "var(--shadow-4)",
        "5": "var(--shadow-5)",
        soft: "var(--shadow-soft)",
        medium: "var(--shadow-medium)",
        strong: "var(--shadow-strong)",
        floating: "var(--shadow-floating)",
        glass: "var(--shadow-glass)",
        "ai-card": "var(--shadow-ai-card)",
        dialog: "var(--shadow-dialog)",
        dropdown: "var(--shadow-dropdown)",
        modal: "var(--shadow-modal)",
        hover: "var(--shadow-hover)",
        focus: "var(--shadow-focus)",
      },
      fontFamily: {
        sans: ["var(--font-family-sans)", "system-ui", "sans-serif"],
        mono: ["var(--font-family-mono)", "monospace"],
      },
      fontSize: {
        display: ["var(--font-size-display)", { lineHeight: "var(--line-height-display)", fontWeight: "var(--font-weight-display)", letterSpacing: "var(--letter-spacing-display)" }],
        "heading-1": ["var(--font-size-h1)", { lineHeight: "var(--line-height-h1)", fontWeight: "var(--font-weight-h1)", letterSpacing: "var(--letter-spacing-h1)" }],
        "heading-2": ["var(--font-size-h2)", { lineHeight: "var(--line-height-h2)", fontWeight: "var(--font-weight-h2)", letterSpacing: "var(--letter-spacing-h2)" }],
        "heading-3": ["var(--font-size-h3)", { lineHeight: "var(--line-height-h3)", fontWeight: "var(--font-weight-h3)", letterSpacing: "var(--letter-spacing-h3)" }],
        "heading-4": ["var(--font-size-h4)", { lineHeight: "var(--line-height-h4)", fontWeight: "var(--font-weight-h4)", letterSpacing: "var(--letter-spacing-h4)" }],
        subtitle: ["var(--font-size-subtitle)", { lineHeight: "var(--line-height-subtitle)", fontWeight: "var(--font-weight-subtitle)", letterSpacing: "var(--letter-spacing-subtitle)" }],
        "body-large": ["var(--font-size-body-large)", { lineHeight: "var(--line-height-body-large)", fontWeight: "var(--font-weight-body-large)", letterSpacing: "var(--letter-spacing-body-large)" }],
        body: ["var(--font-size-body)", { lineHeight: "var(--line-height-body)", fontWeight: "var(--font-weight-body)", letterSpacing: "var(--letter-spacing-body)" }],
        "body-small": ["var(--font-size-body-small)", { lineHeight: "var(--line-height-body-small)", fontWeight: "var(--font-weight-body-small)", letterSpacing: "var(--letter-spacing-body-small)" }],
        caption: ["var(--font-size-caption)", { lineHeight: "var(--line-height-caption)", fontWeight: "var(--font-weight-caption)", letterSpacing: "var(--letter-spacing-caption)" }],
        label: ["var(--font-size-label)", { lineHeight: "var(--line-height-label)", fontWeight: "var(--font-weight-label)", letterSpacing: "var(--letter-spacing-label)" }],
        button: ["var(--font-size-button)", { lineHeight: "var(--line-height-button)", fontWeight: "var(--font-weight-button)", letterSpacing: "var(--letter-spacing-button)" }],
        code: ["var(--font-size-code)", { lineHeight: "var(--line-height-code)", fontWeight: "var(--font-weight-code)", letterSpacing: "var(--letter-spacing-code)" }],
        overline: ["var(--font-size-overline)", { lineHeight: "var(--line-height-overline)", fontWeight: "var(--font-weight-overline)", letterSpacing: "var(--letter-spacing-overline)" }],
        smallest: ["var(--font-size-smallest)", { lineHeight: "var(--line-height-smallest)", fontWeight: "var(--font-weight-smallest)", letterSpacing: "var(--letter-spacing-smallest)" }],
      },
      spacing: {
        "0": "var(--space-0)",
        "1": "var(--space-1)",
        "2": "var(--space-2)",
        "3": "var(--space-3)",
        "4": "var(--space-4)",
        "5": "var(--space-5)",
        "6": "var(--space-6)",
        "7": "var(--space-7)",
        "8": "var(--space-8)",
        "9": "var(--space-9)",
        "10": "var(--space-10)",
        "11": "var(--space-11)",
        "12": "var(--space-12)",
        "13": "var(--space-13)",
        "14": "var(--space-14)",
      },
      width: {
        "icon-xs": "var(--icon-xs)",
        "icon-sm": "var(--icon-sm)",
        "icon-md": "var(--icon-md)",
        "icon-lg": "var(--icon-lg)",
        "icon-xl": "var(--icon-xl)",
        "avatar-xs": "var(--avatar-xs)",
        "avatar-sm": "var(--avatar-sm)",
        "avatar-md": "var(--avatar-md)",
        "avatar-lg": "var(--avatar-lg)",
        "avatar-xl": "var(--avatar-xl)",
        "avatar-2xl": "var(--avatar-2xl)",
      },
      height: {
        "icon-xs": "var(--icon-xs)",
        "icon-sm": "var(--icon-sm)",
        "icon-md": "var(--icon-md)",
        "icon-lg": "var(--icon-lg)",
        "icon-xl": "var(--icon-xl)",
        "avatar-xs": "var(--avatar-xs)",
        "avatar-sm": "var(--avatar-sm)",
        "avatar-md": "var(--avatar-md)",
        "avatar-lg": "var(--avatar-lg)",
        "avatar-xl": "var(--avatar-xl)",
        "avatar-2xl": "var(--avatar-2xl)",
        "button-xs": "var(--button-xs)",
        "button-sm": "var(--button-sm)",
        "button-md": "var(--button-md)",
        "button-lg": "var(--button-lg)",
        "button-xl": "var(--button-xl)",
        "input-sm": "var(--input-sm)",
        "input-md": "var(--input-md)",
        "input-lg": "var(--input-lg)",
      },
      minWidth: {
        "card-sm": "var(--card-sm)",
        "card-md": "var(--card-md)",
        "card-lg": "var(--card-lg)",
        "button-xs": "var(--button-xs)",
        "button-sm": "var(--button-sm)",
        "button-md": "var(--button-md)",
        "button-lg": "var(--button-lg)",
        "button-xl": "var(--button-xl)",
      },
      maxWidth: {
        "container-sm": "var(--container-max-width-sm)",
        "container-md": "var(--container-max-width-md)",
        "container-lg": "var(--container-max-width-lg)",
        "container-xl": "var(--container-max-width-xl)",
        "container-2xl": "var(--container-max-width-2xl)",
      },
      zIndex: {
        base: "0",
        dropdown: "1000",
        sticky: "1100",
        banner: "1200",
        overlay: "1300",
        modal: "1400",
        popover: "1500",
        skipLink: "1600",
        toast: "1700",
        tooltip: "1800",
      },
      backdropBlur: {
        sm: "var(--blur-sm)",
        md: "var(--blur-md)",
        lg: "var(--blur-lg)",
        xl: "var(--blur-xl)",
        "2xl": "var(--blur-2xl)",
        "3xl": "var(--blur-3xl)",
      },
      opacity: {
        "0": "var(--opacity-0)",
        "5": "var(--opacity-5)",
        "10": "var(--opacity-10)",
        "15": "var(--opacity-15)",
        "20": "var(--opacity-20)",
        "25": "var(--opacity-25)",
        "30": "var(--opacity-30)",
        "40": "var(--opacity-40)",
        "50": "var(--opacity-50)",
        "60": "var(--opacity-60)",
        "70": "var(--opacity-70)",
        "75": "var(--opacity-75)",
        "80": "var(--opacity-80)",
        "90": "var(--opacity-90)",
        "95": "var(--opacity-95)",
        "100": "var(--opacity-100)",
      },
      transitionDuration: {
        instant: "var(--duration-instant)",
        fast: "var(--duration-fast)",
        normal: "var(--duration-normal)",
        slow: "var(--duration-slow)",
        "x-slow": "var(--duration-x-slow)",
        "xx-slow": "var(--duration-xx-slow)",
      },
      transitionDelay: {
        instant: "var(--delay-instant)",
        fast: "var(--delay-fast)",
        normal: "var(--delay-normal)",
        slow: "var(--delay-slow)",
        "x-slow": "var(--delay-x-slow)",
      },
      transitionTimingFunction: {
        "ease-out-custom": "var(--easing-ease-out)",
        "ease-in-custom": "var(--easing-ease-in)",
        "ease-in-out-custom": "var(--easing-ease-in-out)",
        spring: "var(--easing-spring)",
      },
      borderWidth: {
        "0": "var(--border-width-0)",
        "1": "var(--border-width-1)",
        "2": "var(--border-width-2)",
        "4": "var(--border-width-4)",
        "8": "var(--border-width-8)",
      },
      strokeWidth: {
        "1": "var(--stroke-1)",
        "1-5": "var(--stroke-1-5)",
        "2": "var(--stroke-2)",
        "3": "var(--stroke-3)",
      },
      keyframes: {
        "skeleton-pulse": {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0.5" },
        },
        "spinner-rotate": {
          "0%": { transform: "rotate(0deg)" },
          "100%": { transform: "rotate(360deg)" },
        },
        "fade-in": {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        "fade-out": {
          "0%": { opacity: "1" },
          "100%": { opacity: "0" },
        },
        "slide-in-from-top": {
          "0%": { transform: "translateY(-10px)", opacity: "0" },
          "100%": { transform: "translateY(0)", opacity: "1" },
        },
        "slide-in-from-bottom": {
          "0%": { transform: "translateY(10px)", opacity: "0" },
          "100%": { transform: "translateY(0)", opacity: "1" },
        },
        "slide-in-from-left": {
          "0%": { transform: "translateX(-10px)", opacity: "0" },
          "100%": { transform: "translateX(0)", opacity: "1" },
        },
        "slide-in-from-right": {
          "0%": { transform: "translateX(10px)", opacity: "0" },
          "100%": { transform: "translateX(0)", opacity: "1" },
        },
        "scale-in": {
          "0%": { transform: "scale(0.95)", opacity: "0" },
          "100%": { transform: "scale(1)", opacity: "1" },
        },
      },
      animation: {
        "skeleton-pulse": "skeleton-pulse var(--duration-xx-slow) ease-in-out infinite",
        "spinner-rotate": "spinner-rotate var(--duration-xx-slow) linear infinite",
        "fade-in": "fade-in var(--duration-normal) var(--easing-ease-out)",
        "fade-out": "fade-out var(--duration-fast) var(--easing-ease-in)",
        "slide-in-from-top": "slide-in-from-top var(--duration-normal) var(--easing-ease-out)",
        "slide-in-from-bottom": "slide-in-from-bottom var(--duration-normal) var(--easing-ease-out)",
        "slide-in-from-left": "slide-in-from-left var(--duration-normal) var(--easing-ease-out)",
        "slide-in-from-right": "slide-in-from-right var(--duration-normal) var(--easing-ease-out)",
        "scale-in": "scale-in var(--duration-normal) var(--easing-ease-out)",
      },
    },
  },
  plugins: [animate],
};

export default config;
